---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(ggplot2)

source("C:/Users/d.vitali/Desktop/Github/CRIISP-WP6/Sensors-API/Withings-API/withings_func.R")

```

set participant data folder
```{r}
#folder_name<-"data_ART_1727097278"
#  start_date<-"2024-08-30 06:00:00"
#  end_date  <-"2024-09-08 06:00:00"

#folder_name<-"data_VIV_1727185308"
#  start_date<-"2024-08-30 06:00:00"
#  end_date  <-"2024-09-08 06:00:00"

#folder_name<-"data_JAA_1727098304"
#  start_date<-"2024-08-30 06:00:00"
#  end_date  <-"2024-09-08 06:00:00"

folder_name<-"data_CEC_1727186111"
  start_date<-"2024-08-29 06:00:00"
  end_date  <-"2024-09-08 06:00:00"




path<-paste0("C:/Users/d.vitali/Downloads/",folder_name,"/")


```


# STEPS
ad hoc (whenever more than 0 step is recorded)
```{r}
# Sample data
steps_csv <- read.csv(file = paste0(path,"raw_tracker_steps.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
steps_csv$start <- ymd_hms(steps_csv$start,  tz = "UTC")

steps_data<-expand_csv_data(steps_csv) %>%
  filter(timestamp < end_date & timestamp > start_date)

steps_data %>%
  # Create a new column 'day' that groups by date
  mutate(day = as.Date(timestamp)) %>%
  # Group by day
  group_by(day) %>%
  # Count non-NA values in the heart_rate column
  summarise(non_na_count = sum(!is.na(value)))

```

# BODY temperature
monitored  ~ 1400/day (~58/hr)

```{r}
# Sample data
temperature_csv <- read.csv(file = paste0(path,"raw_core_body_temperature_Core body temperature.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
temperature_csv$start <- ymd_hms(temperature_csv$start,  tz = "UTC")

temperature_data<-expand_csv_data(temperature_csv) %>%
  filter(timestamp < end_date & timestamp > start_date)

temperature_data %>%
  # Create a new column 'day' that groups by date
  mutate(day = as.Date(timestamp)) %>%
  # Group by day
  group_by(day) %>%
  # Count non-NA values in the heart_rate column
  summarise(non_na_count = sum(!is.na(value)))

```

# Heart Rate
monitored  ~ 140/day (~6/hr)

```{r}
# Sample data
HR_csv <- read.csv(file = paste0(path,"raw_hr_hr.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
HR_csv$start <- ymd_hms(HR_csv$start,  tz = "UTC")

HR_data<-expand_csv_data(HR_csv) %>%
  filter(timestamp < end_date & timestamp > start_date)


HR_data %>%
  # Create a new column 'day' that groups by date
  mutate(day = as.Date(timestamp)) %>%
  # Group by day
  group_by(day) %>%
  # Count non-NA values in the heart_rate column
  summarise(non_na_count = sum(!is.na(value)))

```

# Activity Intensity
monitored  ~ 200/day (~8/hr)
```{r}
# Sample data
activity_intensity_csv <- read.csv(file = paste0(path,"raw_tracker_Activity Intensity.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
activity_intensity_csv$start <- ymd_hms(activity_intensity_csv$start,  tz = "UTC")

activity_intensity_data<-expand_csv_data(activity_intensity_csv) %>%
  filter(timestamp < end_date & timestamp > start_date)

activity_intensity_data%>%
  # Create a new column 'day' that groups by date
  mutate(day = as.Date(timestamp)) %>%
  # Group by day
  group_by(day) %>%
  # Count non-NA values in the heart_rate column
  summarise(non_na_count = sum(!is.na(value)))

```

# Sleep states
```{r}
# Sample data
sleepstate_csv <- read.csv(file = paste0(path,"raw_tracker_sleep-state.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
sleepstate_csv$start <- ymd_hms(sleepstate_csv$start,  tz = "UTC")

sleepstate_data<-expand_csv_data(sleepstate_csv) %>%
  filter(timestamp < end_date & timestamp > start_date)

sleepstate_data %>%
  # Create a new column 'day' that groups by date
  mutate(day = as.Date(timestamp)) %>%
  # Group by day
  group_by(day) %>%
  # Count non-NA values in the heart_rate column
  summarise(non_na_count = sum(!is.na(value)))

```

## Sleep summary
```{r}
# Sample data
sleepsummary_data <- read.csv(file = paste0(path,"sleep.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
sleepsummary_data$from <- ymd_hms(sleepsummary_data$from,  tz = "UTC")

sleepsummary_data$to <- ymd_hms(sleepsummary_data$to,  tz = "UTC")

sleepsummary_data<-sleepsummary_data %>%
  filter(from < end_date & from > start_date)


```

# ECG
```{r}
# Sample data
ECG_csv <- read.csv(file = paste0(path,"signal.csv"), header = TRUE, sep = ",")

# Convert date column to datetime
ECG_csv$date <- ymd_hms(ECG_csv$date,  tz = "UTC") 

ECG_data<-as_tibble(ECG_csv)%>%
  filter(date < end_date & date > start_date)


```


# Merge steps, activity, hr, temperature
```{r}

act_data <- full_join(steps_data, activity_intensity_data, by = "timestamp")

colnames(act_data)<-c("timestamp","steps","activity_int")

act_data <- full_join(act_data, temperature_data, by = "timestamp")

colnames(act_data)<-c("timestamp","steps","activity_int","temperature")

act_data <- full_join(act_data, HR_data, by = "timestamp")

colnames(act_data)<-c("timestamp","steps","activity_int","temperature","hr")


```




```{r}

plot_data<-act_data

# Reshape the data for faceting
act_data_long <- plot_data %>%
  pivot_longer(cols = c(activity_int, steps, temperature, hr),
               names_to = "metric",
               values_to = "value")

# Create the plot with facets
ggplot(act_data_long, aes(x = timestamp, y = value)) +
  
  geom_point(data = act_data_long %>% filter(metric == "activity_int"), 
           aes(fill = metric)) +
  
  geom_point(data = act_data_long %>% filter(metric == "steps"), 
           aes(fill = metric)) +
  
  geom_point(data = act_data_long %>% filter(metric == "temperature"), 
            aes(color = metric)) +
  
  geom_point(data = act_data_long %>% filter(metric == "hr"), 
             aes(color = metric)) +
  
  # Labels and theme
  labs(title = "activity_int, steps, Temperature, and Heart Rate Over Time",
       x = "Time",
       y = "Value",
       color = "Metrics",
       fill = "Metrics") +
  
  # Facet by metric
  facet_wrap(~ metric, scales = "free_y", nrow = 4) +
  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


# explore missing hr datapoints
```{r}
act_data_NA<-act_data %>% filter(!is.na(hr))
act_data_NA <- act_data_NA %>%
  arrange(timestamp) %>%  
  mutate(minutes_diff = as.numeric(difftime(timestamp, lag(timestamp), units = "mins")))

ggplot(act_data_NA, aes(x = timestamp, y = minutes_diff)) +
  geom_line() +
  scale_y_continuous(breaks = seq(0, max(act_data_NA$minutes_diff, na.rm = TRUE), by = 10)) + 
  labs(title = "Time Difference Between HR Observations", 
       x = "Timestamp", 
       y = "Minutes Difference") +
  theme_minimal()


```

# explore missing Temperature datapoints
```{r}
act_data_NA<-act_data %>% filter(!is.na(temperature))
act_data_NA <- act_data_NA %>%
  arrange(timestamp) %>%  
  mutate(minutes_diff = as.numeric(difftime(timestamp, lag(timestamp), units = "mins")))

ggplot(act_data_NA, aes(x = timestamp, y = minutes_diff)) +
  geom_line() +
  scale_y_continuous(breaks = seq(0, max(act_data_NA$minutes_diff, na.rm = TRUE), by = 10)) + 
  labs(title = "Time Difference Between Temp Observations", 
       x = "Timestamp", 
       y = "Minutes Difference") +
  theme_minimal()


```





# OTHER derived
```{r}
# Sample data
distance_csv <- read.csv(file = paste0(path,"raw_tracker_distance.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
distance_csv$start <- ymd_hms(distance_csv$start,  tz = "UTC")

distance_data<-expand_csv_data(distance_csv)

```
```{r}
# Sample data
elevation_csv <- read.csv(file = paste0(path,"raw_elevation_Elevation.csv"), header = TRUE, sep = ",")

# Convert start column to datetime
elevation_csv$start <- ymd_hms(elevation_csv$start,  tz = "UTC")


elevation_data<-expand_csv_data(elevation_csv)
```