---
title: "Python withingsAPI"
output: 
  github_document:
    toc: True
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
```{r echo=F}
install.packages("reticulate")

library(reticulate)

```
Python withings-api Build status Coverage Status PyPI Python library for the Withings Health API

Withings Health API https://developer.withings.com/oauth2/

Uses OAuth 2.0 to authenticate. You need to obtain a client id and consumer secret from Withings by creating an application here: http://developer.withings.com/oauth2/

    pip install withings-api


## Withings pulse HR

## Prerequisites

Before being able to use this package, and the Withings Health Mate API, you will need to create a Withings account and a Withings developer app. Instructions are provided in the [developer's guide](http://developer.withings.com/oauth2/).

Note: when setting up an app, the Callback URL should be set to http://localhost:1410/. This is not supposed to be allowed, but it does seems to work, and I haven't been able to make it work using another address. 

## API plans
Withings Standard/Free Plan

Withings Standard/Free Plan includes:

* 5000 active users 
* 120 requests per minute for your API project 

## Security and compliance

### Withings EU Medical Cloud / Public Cloud (HIPAA/HDS)
Based in France, our EU Medical Cloud / Public Cloud is **GDPR compliant**, HDS, HIPAA and ISO 27001:2017 certified.
By design, our privacy policy ensures that user data is safely collected.

### Withings US Medical Cloud (HIPAA)

Withings complies with HIPAA rules and regulations so that our services can be more effectively integrated by entities that are covered by HIPAA. Our US Medical Cloud is a US based, ISO 27001:2017 certified and HIPAA compliant.



## API SPECS

DATA is fetched from Cloud not from the device directly (no websocket on dev)

Free for providers with under 5,000 users.


## API integration

### Create your Application
First, create the Withings account that will be used for your integration. Although using your personal Withings account is possible, we recommend that you create a new account for your organization. Creating an Application will provide you with a cliendId and client_secret that you will use to access our services.

#### Target endpoint

Please use the following endpoint for all requests you will perform on our APIs :

https://wbsapi.withings.net

## Use

### Callback URL

Note: when setting up an app, the Callback URL should be set to http://localhost:1410/. This is not supposed to be allowed, but it does seems to work. This is handy because allows for the callback to be (e.g.) on a laptop for testing.

```{python }

from withings_api import WithingsAuth, WithingsApi, AuthScope
from withings_api.common import get_measure_value, MeasureType

auth = WithingsAuth(
    client_id='',
    consumer_secret='',
    callback_uri='http://localhost:1410/', # localhost restricts to 10 users
    mode='demo',  # Used for testing. Remove this when getting real user data.
    scope=(
        AuthScope.USER_ACTIVITY,
        AuthScope.USER_METRICS,
        AuthScope.USER_INFO,
        AuthScope.USER_SLEEP_EVENTS,
    )
)

authorize_url = auth.get_authorize_url()
# Have the user goto authorize_url and authorize the app. They will be redirected back to your redirect_uri.

credentials = auth.get_credentials('https://wbsapi.withings.net')

# Now you are ready to make calls for data.
api = WithingsApi(credentials)

meas_result = api.measure_get_meas()
weight_or_none = get_measure_value(meas_result, with_measure_type=MeasureType.WEIGHT)
